const C={"Comidas":["Feijoada","Pizza","Sushi","Churrasco","Lasanha","Pastel"],"Animais":["Cachorro","Gato","Elefante","Girafa","Tubarão","Pinguim"],"Filmes":["Titanic","Avatar","Shrek","Matrix","Frozen","Gladiador"],"Lugares":["Praia","Hospital","Escola","Aeroporto","Shopping","Estádio"],"Games":["Minecraft","Fortnite","GTA","Mario","The Sims","DayZ"],"Objetos":["Guarda-chuva","Celular","Martelo","Geladeira","Mochila","Relógio"],"Profissões":["Médico","Professor","Bombeiro","Piloto","Chef","Detetive"],"Esportes":["Futebol","Vôlei","Tênis","Natação","Basquete","Surfe"]};
const icons={Comidas:'🍔',Animais:'🐶',Filmes:'🎬',Lugares:'🌎',Games:'🎮',Objetos:'🎒',Profissões:'👨‍🚒',Esportes:'⚽'};
let S={players:['Jogador 1','Jogador 2','Jogador 3','Jogador 4','Jogador 5'],selected:[],imps:1,roles:[],word:'',cat:'',idx:0,order:[],voter:0,votes:[],civ:0,imp:0,timer:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], rnd=a=>a[Math.floor(Math.random()*a.length)], shuffle=a=>[...a].sort(()=>Math.random()-.5);
function go(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0);if(id==='players')renderPlayers();if(id==='categories')syncPlayers();if(id==='votePass')prepareVotePass()}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function renderPlayers(){let d=$('#playerList');d.innerHTML='';S.players.forEach((n,i)=>{let x=document.createElement('input');x.value=n;x.placeholder=`Jogador ${i+1}`;x.oninput=()=>S.players[i]=x.value;d.append(x)})}
function syncPlayers(){S.players=$$('#playerList input').map((x,i)=>x.value.trim()||`Jogador ${i+1}`)}
$('#addPlayer').onclick=()=>{syncPlayers();if(S.players.length<15){S.players.push(`Jogador ${S.players.length+1}`);renderPlayers()}};
Object.keys(C).forEach(k=>{let b=document.createElement('button');b.className='cat';b.innerHTML=`<i>${icons[k]}</i>${k}`;b.onclick=()=>{b.classList.toggle('on');S.selected=b.classList.contains('on')?[...S.selected,k]:S.selected.filter(x=>x!==k)};$('#categoryGrid').append(b)});
$('#impMinus').onclick=()=>{S.imps=Math.max(1,S.imps-1);$('#impCount').textContent=S.imps};$('#impPlus').onclick=()=>{S.imps=Math.min(Math.max(1,S.players.length-2),S.imps+1);$('#impCount').textContent=S.imps};
function setupRound(){syncPlayers();if(S.players.length<3)return alert('Adicione pelo menos 3 jogadores.');S.imps=Math.min(S.imps,S.players.length-2);let custom=$('#customWords').value.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean);if(custom.length){S.cat='Personalizada';S.word=rnd(custom)}else{let cats=S.selected.length?S.selected:Object.keys(C);S.cat=rnd(cats);S.word=rnd(C[S.cat])}let noImp=$('#chaos').checked&&Math.random()<.2;let impIdx=noImp?[]:shuffle(S.players.map((_,i)=>i)).slice(0,S.imps);S.roles=S.players.map((n,i)=>({name:n,imp:impIdx.includes(i)}));S.idx=0;S.votes=[];S.voter=0;showReveal()}
$('#start').onclick=setupRound;
function showReveal(){go('reveal');let r=S.roles[S.idx];$('#revealProgress').textContent=`Jogador ${S.idx+1} de ${S.players.length}`;$('#revealName').textContent=r.name;$('#hidden').hidden=false;$('#shown').hidden=true;$('#nextReveal').disabled=true}
function reveal(on){let r=S.roles[S.idx];if(on){$('#hidden').hidden=true;$('#shown').hidden=false;let mystery=$('#mystery').checked;if(r.imp&&!mystery){let extra=$('#showCat').checked?`<p>Categoria: <b>${S.cat}</b></p>`:'';let mates=$('#knowEach').checked?S.roles.filter(x=>x.imp&&x!==r).map(x=>x.name).join(', '):'';$('#shown').innerHTML=`<div class="role imp">😈 VOCÊ É O IMPOSTOR</div><div class="secret">IMPOSTOR</div>${extra}${mates?`<p>Outro impostor: <b>${mates}</b></p>`:''}`}else{let w=r.imp&&mystery?decoy():S.word;$('#shown').innerHTML=`<div class="role civ">🔐 SUA PALAVRA</div><div class="secret">${w}</div><p>${S.cat}</p>`}navigator.vibrate?.(r.imp?[80,50,80]:35)}else{$('#shown').hidden=true;$('#hidden').hidden=false;$('#nextReveal').disabled=false}}
function decoy(){let pool=C[S.cat]||Object.values(C).flat();return rnd(pool.filter(x=>x!==S.word))||'Mistério'}
let card=$('#revealCard');['pointerdown'].forEach(e=>card.addEventListener(e,x=>{x.preventDefault();reveal(true)}));['pointerup','pointercancel','pointerleave'].forEach(e=>card.addEventListener(e,()=>reveal(false)));
$('#nextReveal').onclick=()=>{S.idx++;if(S.idx<S.roles.length)showReveal();else{S.order=shuffle(S.players);$('#starterName').textContent=S.order[0];go('starter')}};
$('#beginDiscussion').onclick=()=>{go('discussion');$('#order').innerHTML=S.order.map(x=>`<li>${x}</li>`).join('');startTimer(+$('#time').value)};
function startTimer(sec){clearInterval(S.timer);let left=sec;const paint=()=>{$('#timer').textContent=sec?`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`:'∞';$('#timer').classList.toggle('low',sec&&left<=20)};paint();if(sec)S.timer=setInterval(()=>{left--;paint();if(left<=0){clearInterval(S.timer);navigator.vibrate?.([200,100,200])}},1000)}
function prepareVotePass(){clearInterval(S.timer);$('#votePassName').textContent=S.players[S.voter]}
$('#openVote').onclick=()=>{go('vote');$('#voterName').textContent=S.players[S.voter];$('#voteList').innerHTML='';S.players.forEach((n,i)=>{if(i===S.voter)return;let b=document.createElement('button');b.textContent=n;b.onclick=()=>castVote(i);$('#voteList').append(b)})};
function castVote(i){S.votes.push(i);S.voter++;if(S.voter<S.players.length)go('votePass');else finishVote()}
function finishVote(){let counts=S.players.map((_,i)=>S.votes.filter(v=>v===i).length),max=Math.max(...counts),ties=counts.map((v,i)=>v===max?i:-1).filter(i=>i>=0),acc=rnd(ties),caught=S.roles[acc].imp;go('result');$('#accused').textContent=S.players[acc];$('#resultIcon').textContent=caught?'😈':'😇';$('#verdict').className='verdict '+(caught?'win':'lose');$('#verdict').textContent=caught?'ERA O IMPOSTOR!':'NÃO ERA O IMPOSTOR!';if(caught){$('#lastChance').hidden=false}else{$('#lastChance').hidden=true;S.imp++;renderScore()}if(!S.roles.some(x=>x.imp)){S.civ++;$('#verdict').textContent='NÃO HAVIA IMPOSTOR!';renderScore()}}
$('#guessBtn').onclick=()=>{let ok=$('#guess').value.trim().localeCompare(S.word,undefined,{sensitivity:'base'})===0;if(ok){S.imp++;$('#verdict').className='verdict lose';$('#verdict').textContent='😈 IMPOSTOR VIROU O JOGO!'}else{S.civ++;$('#verdict').className='verdict win';$('#verdict').textContent=`🎉 CIVIS VENCERAM! A palavra era ${S.word}.`}$('#lastChance').hidden=true;renderScore()};
function renderScore(){$('#score').innerHTML=`<div><strong>${S.civ}</strong><span>Civis</span></div><div><strong>${S.imp}</strong><span>Impostores</span></div>`}
$('#newRound').onclick=()=>{S.votes=[];$('#guess').value='';setupRound()};$('#how').onclick=()=>$('#help').showModal();$('#closeHelp').onclick=()=>$('#help').close();renderPlayers();renderScore();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});