const C={
"Comidas":["Feijoada","Pizza","Sushi","Churrasco","Lasanha","Pastel","Hambúrguer","Cachorro-quente","Strogonoff","Risoto","Panqueca","Coxinha","Brigadeiro","Pudim","Sorvete","Bolo","Tacos","Macarrão","Batata frita","Pão de queijo","Acarajé","Moqueca","Escondidinho","Tapioca","Churros","Paella","Ravioli","Kebab","Nachos","Fondue"],
"Animais":["Cachorro","Gato","Elefante","Girafa","Tubarão","Pinguim","Leão","Tigre","Macaco","Cavalo","Vaca","Porco","Coelho","Urso","Lobo","Raposa","Canguru","Panda","Golfinho","Baleia","Polvo","Crocodilo","Cobra","Águia","Coruja","Papagaio","Tartaruga","Rinoceronte","Hipopótamo","Camaleão"],
"Filmes":["Titanic","Avatar","Shrek","Matrix","Frozen","Gladiador","Vingadores","Homem-Aranha","Batman","Superman","Toy Story","O Rei Leão","Jurassic Park","Harry Potter","Senhor dos Anéis","Star Wars","De Volta para o Futuro","Rocky","Interestelar","Procurando Nemo","Os Incríveis","Piratas do Caribe","Transformers","Deadpool","Crepúsculo","Jogos Vorazes","Missão Impossível","Velozes e Furiosos","O Máskara","Esqueceram de Mim"],
"Lugares":["Praia","Hospital","Escola","Aeroporto","Shopping","Estádio","Cinema","Restaurante","Supermercado","Academia","Biblioteca","Hotel","Delegacia","Parque","Zoológico","Museu","Teatro","Igreja","Padaria","Farmácia","Posto de gasolina","Banco","Rodoviária","Metrô","Universidade","Castelo","Fazenda","Floresta","Deserto","Ilha"],
"Games":["Minecraft","Fortnite","GTA","Mario","The Sims","DayZ","Counter-Strike","Valorant","League of Legends","Dota","PUBG","Call of Duty","Battlefield","FIFA","Minecraft","Terraria","Roblox","Among Us","The Last of Us","God of War","Red Dead Redemption","Cyberpunk 2077","Elden Ring","Dark Souls","Resident Evil","Mortal Kombat","Street Fighter","Sonic","Zelda","Pokémon"],
"Objetos":["Guarda-chuva","Celular","Martelo","Geladeira","Mochila","Relógio","Computador","Televisão","Cadeira","Mesa","Garrafa","Tesoura","Chave","Óculos","Fone de ouvido","Controle remoto","Ventilador","Espelho","Panela","Vassoura","Travesseiro","Cobertor","Caneta","Livro","Lanterna","Capacete","Mala","Câmera","Calculadora","Micro-ondas"],
"Profissões":["Médico","Professor","Bombeiro","Piloto","Chef","Detetive","Policial","Engenheiro","Programador","Advogado","Dentista","Veterinário","Enfermeiro","Arquiteto","Jornalista","Fotógrafo","Mecânico","Eletricista","Padeiro","Garçom","Motorista","Astronauta","Cientista","Ator","Cantor","Pedreiro","Designer","Psicólogo","Agricultor","Juiz"],
"Esportes":["Futebol","Vôlei","Tênis","Natação","Basquete","Surfe","Fórmula 1","Boxe","MMA","Judô","Karatê","Skate","Ciclismo","Atletismo","Handebol","Golfe","Rugby","Beisebol","Hóquei","Tênis de mesa","Futsal","Ginástica","Hipismo","Esqui","Snowboard","Triatlo","Badminton","Escalada","Arco e flecha","Motocross"],
"Carros":["Ferrari","Porsche","Mustang","Civic","Corolla","Camaro","Fusca","Uno","Gol","Onix","HB20","Jeep Renegade","Hilux","Ranger","Saveiro","BMW","Mercedes-Benz","Lamborghini","Audi","Tesla","Maverick","Opala","Chevette","Kombi","Land Rover","Mini Cooper","Supra","Skyline","Viper","Corvette"],
"Tecnologia":["Internet","Wi-Fi","Bluetooth","Inteligência Artificial","Robô","Drone","Notebook","Smartphone","Tablet","Impressora 3D","GPS","Pendrive","QR Code","Nuvem","Banco de dados","Servidor","Roteador","Processador","Placa de vídeo","Teclado","Mouse","Monitor","Webcam","Microfone","Realidade virtual","Satélite","Fibra óptica","Código de barras","Smartwatch","Console"],
"Música":["Violão","Guitarra","Bateria","Piano","Saxofone","Violino","Flauta","Trompete","Rock","Samba","Pagode","Sertanejo","Funk","Rap","Pop","Jazz","Reggae","Forró","DJ","Karaokê","Show","Festival","Microfone","Banda","Orquestra","Cantor","Refrão","Solo","Disco","Playlist"],
"Personagens":["Homem-Aranha","Batman","Superman","Hulk","Thor","Homem de Ferro","Capitão América","Deadpool","Wolverine","Coringa","Darth Vader","Harry Potter","Shrek","Mario","Sonic","Pikachu","Mickey","Simba","Elsa","Buzz Lightyear","Woody","Goku","Vegeta","Naruto","Scooby-Doo","Bob Esponja","Jack Sparrow","Indiana Jones","Rambo","Rocky Balboa"],
"Países":["Brasil","Argentina","Uruguai","Chile","México","Estados Unidos","Canadá","Portugal","Espanha","França","Itália","Alemanha","Inglaterra","Grécia","Egito","Japão","China","Índia","Austrália","Rússia","Suíça","Holanda","Bélgica","Noruega","Suécia","Coreia do Sul","África do Sul","Turquia","Tailândia","Nova Zelândia"],
"Natureza":["Montanha","Vulcão","Cachoeira","Rio","Lago","Oceano","Floresta","Deserto","Ilha","Caverna","Geleira","Arco-íris","Tornado","Furacão","Terremoto","Neve","Chuva","Relâmpago","Nuvem","Sol","Lua","Estrela","Praia","Pedra","Árvore","Flor","Folha","Areia","Fogo","Gelo"],
"Casa":["Sofá","Cama","Geladeira","Fogão","Televisão","Chuveiro","Vaso sanitário","Guarda-roupa","Mesa","Cadeira","Janela","Porta","Tapete","Almofada","Travesseiro","Espelho","Lâmpada","Ventilador","Ar-condicionado","Máquina de lavar","Micro-ondas","Liquidificador","Cafeteira","Panela","Talher","Prato","Copo","Toalha","Vassoura","Varal"]
};
const icons={Comidas:'🍔',Animais:'🐶',Filmes:'🎬',Lugares:'🌎',Games:'🎮',Objetos:'🎒',Profissões:'👨‍🚒',Esportes:'⚽',Carros:'🚗',Tecnologia:'💻',Música:'🎵',Personagens:'🦸',Países:'🌍',Natureza:'🌿',Casa:'🏠'};
let S={players:['Jogador 1','Jogador 2','Jogador 3','Jogador 4','Jogador 5'],selected:[],imps:1,roles:[],word:'',cat:'',idx:0,order:[],voter:0,votes:[],civ:0,imp:0,timer:null,lastImps:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], rnd=a=>a[Math.floor(Math.random()*a.length)];
function shuffle(a){let r=[...a];for(let i=r.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}return r}
function go(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');scrollTo(0,0);if(id==='players')renderPlayers();if(id==='votePass')prepareVotePass()}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
function renderPlayers(){let d=$('#playerList');d.innerHTML='';S.players.forEach((n,i)=>{let x=document.createElement('input');x.value=n;x.placeholder=`Nome do jogador ${i+1}`;x.setAttribute('aria-label',`Nome do jogador ${i+1}`);x.oninput=()=>{S.players[i]=x.value;$('#playerError').hidden=true};d.append(x)});$('#playerCount').textContent=S.players.length}
function syncPlayers(){S.players=$$('#playerList input').map(x=>x.value.trim())}
function validPlayers(){syncPlayers();let ok=S.players.length>=3&&S.players.every(Boolean);$('#playerError').hidden=ok;if(!ok){let first=$$('#playerList input').find(x=>!x.value.trim());first?.focus()}return ok}
$('#playerMinus').onclick=()=>{syncPlayers();if(S.players.length>3){S.players.pop();renderPlayers()}S.imps=Math.min(S.imps,Math.max(1,S.players.length-2));$('#impCount').textContent=S.imps};
$('#playerPlus').onclick=()=>{syncPlayers();if(S.players.length<15){S.players.push('');renderPlayers();$$('#playerList input').at(-1)?.focus()}};
$('#playersContinue').onclick=()=>{if(validPlayers())go('categories')};
Object.keys(C).forEach(k=>{let b=document.createElement('button');b.className='cat';b.innerHTML=`<i>${icons[k]}</i>${k}`;b.onclick=()=>{b.classList.toggle('on');S.selected=b.classList.contains('on')?[...new Set([...S.selected,k])]:S.selected.filter(x=>x!==k)};$('#categoryGrid').append(b)});
$('#impMinus').onclick=()=>{S.imps=Math.max(1,S.imps-1);$('#impCount').textContent=S.imps};$('#impPlus').onclick=()=>{S.imps=Math.min(Math.max(1,S.players.length-2),S.imps+1);$('#impCount').textContent=S.imps};
function chooseImpostors(noImp){if(noImp)return[];let all=S.players.map((_,i)=>i),pool=all.filter(i=>!S.lastImps.includes(i));if(pool.length<S.imps)pool=all;let chosen=shuffle(pool).slice(0,S.imps);S.lastImps=[...chosen];return chosen}
function setupRound(){if(!validPlayers()){go('players');return}S.imps=Math.min(S.imps,S.players.length-2);$('#impCount').textContent=S.imps;let custom=$('#customWords').value.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean);if(custom.length){S.cat='Personalizada';S.word=rnd(custom)}else{let cats=S.selected.length?S.selected:Object.keys(C);S.cat=rnd(cats);S.word=rnd(C[S.cat])}let noImp=$('#chaos').checked&&Math.random()<.2;let impIdx=chooseImpostors(noImp);S.roles=S.players.map((n,i)=>({name:n,imp:impIdx.includes(i)}));S.idx=0;S.votes=[];S.voter=0;showReveal()}
$('#start').onclick=setupRound;
function impostorHint(){let pool=C[S.cat]||Object.values(C).flat();let hint=rnd(pool.filter(x=>x!==S.word));return hint||S.cat}
function showReveal(){go('reveal');let r=S.roles[S.idx];$('#revealProgress').textContent=`Jogador ${S.idx+1} de ${S.players.length}`;$('#revealName').textContent=r.name;$('#hidden').hidden=false;$('#shown').hidden=true;$('#nextReveal').disabled=true}
function reveal(on){let r=S.roles[S.idx];if(on){$('#hidden').hidden=true;$('#shown').hidden=false;let mystery=$('#mystery').checked;if(r.imp&&!mystery){let extra=$('#showCat').checked?`<p>Categoria: <b>${S.cat}</b></p>`:'';let firstHint=S.idx===0?`<p>💡 Como você é o primeiro da roda, sua dica é: <b>${impostorHint()}</b></p>`:'';let mates=$('#knowEach').checked?S.roles.filter(x=>x.imp&&x!==r).map(x=>x.name).join(', '):'';$('#shown').innerHTML=`<div class="role imp">😈 VOCÊ É O IMPOSTOR</div><div class="secret">IMPOSTOR</div>${extra}${firstHint}${mates?`<p>Outro impostor: <b>${mates}</b></p>`:''}`}else{let w=r.imp&&mystery?decoy():S.word;$('#shown').innerHTML=`<div class="role civ">🔐 SUA PALAVRA</div><div class="secret">${w}</div><p>${S.cat}</p>`}navigator.vibrate?.(r.imp?[80,50,80]:35)}else{$('#shown').hidden=true;$('#hidden').hidden=false;$('#nextReveal').disabled=false}}
function decoy(){let pool=C[S.cat]||Object.values(C).flat();return rnd(pool.filter(x=>x!==S.word))||'Mistério'}
let card=$('#revealCard');card.addEventListener('pointerdown',x=>{x.preventDefault();reveal(true)});['pointerup','pointercancel','pointerleave'].forEach(e=>card.addEventListener(e,()=>reveal(false)));
$('#nextReveal').onclick=()=>{S.idx++;if(S.idx<S.roles.length)showReveal();else{S.order=shuffle(S.players);$('#starterName').textContent=S.order[0];go('starter')}};
$('#beginDiscussion').onclick=()=>{go('discussion');$('#order').innerHTML=S.order.map(x=>`<li>${x}</li>`).join('');startTimer(+$('#time').value)};
function startTimer(sec){clearInterval(S.timer);let left=sec;const paint=()=>{$('#timer').textContent=sec?`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`:'∞';$('#timer').classList.toggle('low',sec&&left<=20)};paint();if(sec)S.timer=setInterval(()=>{left--;paint();if(left<=0){clearInterval(S.timer);navigator.vibrate?.([200,100,200])}},1000)}
function prepareVotePass(){clearInterval(S.timer);$('#votePassName').textContent=S.players[S.voter]}
$('#openVote').onclick=()=>{go('vote');$('#voterName').textContent=S.players[S.voter];$('#voteList').innerHTML='';S.players.forEach((n,i)=>{if(i===S.voter)return;let b=document.createElement('button');b.textContent=n;b.onclick=()=>castVote(i);$('#voteList').append(b)})};
function castVote(i){S.votes.push(i);S.voter++;if(S.voter<S.players.length)go('votePass');else finishVote()}
function finishVote(){let counts=S.players.map((_,i)=>S.votes.filter(v=>v===i).length),max=Math.max(...counts),ties=counts.map((v,i)=>v===max?i:-1).filter(i=>i>=0),acc=rnd(ties),caught=S.roles[acc].imp;go('result');$('#accused').textContent=S.players[acc];$('#resultIcon').textContent=caught?'😈':'😇';$('#verdict').className='verdict '+(caught?'win':'lose');$('#verdict').textContent=caught?'ERA O IMPOSTOR!':'NÃO ERA O IMPOSTOR!';if(caught){$('#lastChance').hidden=false}else{$('#lastChance').hidden=true;S.imp++;renderScore()}if(!S.roles.some(x=>x.imp)){S.civ++;$('#verdict').textContent='NÃO HAVIA IMPOSTOR!';renderScore()}}
$('#guessBtn').onclick=()=>{let ok=$('#guess').value.trim().localeCompare(S.word,undefined,{sensitivity:'base'})===0;if(ok){S.imp++;$('#verdict').className='verdict lose';$('#verdict').textContent='😈 IMPOSTOR VIROU O JOGO!'}else{S.civ++;$('#verdict').className='verdict win';$('#verdict').textContent=`🎉 CIVIS VENCERAM! A palavra era ${S.word}.`}$('#lastChance').hidden=true;renderScore()};
function renderScore(){$('#score').innerHTML=`<div><strong>${S.civ}</strong><span>Civis</span></div><div><strong>${S.imp}</strong><span>Impostores</span></div>`}
$('#newRound').onclick=()=>{S.votes=[];$('#guess').value='';setupRound()};$('#how').onclick=()=>$('#help').showModal();$('#closeHelp').onclick=()=>$('#help').close();renderPlayers();renderScore();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});