const categories ={
  "Comidas":["Feijoada","Pizza","Sushi","Churrasco","Lasanha","Pastel","Hambúrguer","Cachorro-quente","Strogonoff","Risoto","Panqueca","Coxinha","Brigadeiro","Pudim","Sorvete","Bolo","Tacos","Macarrão","Batata frita","Pão de queijo","Acarajé","Moqueca","Escondidinho","Tapioca","Churros","Paella","Ravioli","Kebab","Nachos","Fondue"],
  "Animais":["Cachorro","Gato","Elefante","Girafa","Tubarão","Pinguim","Leão","Tigre","Macaco","Cavalo","Vaca","Porco","Coelho","Urso","Lobo","Raposa","Canguru","Panda","Golfinho","Baleia","Polvo","Crocodilo","Cobra","Águia","Coruja","Papagaio","Tartaruga","Rinoceronte","Hipopótamo","Camaleão"],
  "Filmes":["Titanic","Avatar","Shrek","Matrix","Frozen","Gladiador","Vingadores","Homem-Aranha","Batman","Superman","Toy Story","O Rei Leão","Jurassic Park","Harry Potter","Senhor dos Anéis","Star Wars","De Volta para o Futuro","Rocky","Interestelar","Procurando Nemo","Os Incríveis","Piratas do Caribe","Transformers","Deadpool","Crepúsculo","Jogos Vorazes","Missão Impossível","Velozes e Furiosos","O Máskara","Esqueceram de Mim"],
  "Lugares":["Praia","Hospital","Escola","Aeroporto","Shopping","Estádio","Cinema","Restaurante","Supermercado","Academia","Biblioteca","Hotel","Delegacia","Parque","Zoológico","Museu","Teatro","Igreja","Padaria","Farmácia","Posto de gasolina","Banco","Rodoviária","Metrô","Universidade","Castelo","Fazenda","Floresta","Deserto","Ilha"],
  "Games":["Minecraft","Fortnite","GTA","Mario","The Sims","DayZ","Counter-Strike","Valorant","League of Legends","Dota","PUBG","Call of Duty","Battlefield","FIFA","Minecraft","Terraria","Roblox","Among Us","The Last of Us","God of War","Red Dead Redemption","Cyberpunk 2077","Elden Ring","Dark Souls","Resident Evil","Mortal Kombat","Street Fighter","Sonic","Zelda","Pokémon"],
  "Objetos":["Guarda-chuva","Celular","Martelo","Geladeira","Mochila","Relógio","Computador","Televisão","Cadeira","Mesa","Garrafa","Tesoura","Chave","Óculos","Fone de ouvido","Controle remoto","Ventilador","Espelho","Panela","Vassoura","Travesseiro","Cobertor","Caneta","Livro","Lanterna","Capacete","Mala","Câmera","Calculadora","Micro-ondas"],
  "Profissões":["Médico","Professor","Bombeiro","Piloto","Chef","Detetive","Policial","Engenheiro","Programador","Advogado","Dentista","Veterinário","Enfermeiro","Arquiteto","Jornalista","Fotógrafo","Mecânico","Eletricista","Padeiro","Garçom","Motorista","Astronauta","Cientista","Ator","Cantor","Pedreiro","Designer","Psicólogo","Agricultor","Juiz"],
  "Esportes":["Futebol","Vôlei","Tênis","Natação","Basquete","Surfe","Fórmula 1","Boxe","MMA","Judô","Karatê","Skate","Ciclismo","Atletismo","Handebol","Golfe","Rugby","Beisebol","Hóquei","Tênis de mesa","Futsal","Ginástica","Hipismo","Esqui","Snowboard","Triatlo","Badminton","Escalada","Arco e flecha","Motocross"],
  "Carros":["Ferrari","Porsche","Mustang","Civic","Corolla","Camaro","Fusca","Uno","Gol","Onix","HB20","Jeep Renegade","Hilux","Ranger","Saveiro","BMW","Mercedes-Benz","Lamborghini","Audi","Tesla","Maverick","Opala","Chevette","Kombi","Land Rover","Mini Cooper","Supra","Skyline","Viper","Corvette"],
  "Tecnologia":["Internet","Wi-Fi","Bluetooth","Inteligência Artificial","Robô","Drone","Notebook","Smartphone","Tablet","Impressora 3D","GPS","Pendrive","QR Code","Nuvem","Banco de dados","Servidor","Roteador","Processador","Placa de vídeo","Teclado","Mouse","Monitor","Webcam","Microfone","Realidade virtual","Satélite","Fibra óptica","Código de barras","Smartwatch","Console"],
  "Música":["Violão","Guitarra","Bateria","Piano","Saxofone","Violino","Flauta","Trompete","Rock","Samba","Pagode","Sertanejo","Funk","Rap","Pop","Jazz","Reggae","Forró","DJ","Karaokê","Show","Festival","Microfone","Banda","Orquestra","Cantor","Refrão","Solo","Disco","Playlist"],
  "Personagens":["Homem-Aranha","Batman","Superman","Hulk","Thor","Homem de Ferro","Capitão América","Deadpool","Wolverine","Coringa","Darth Vader","Harry Potter","Shrek","Mario","Sonic","Pikachu","Mickey","Simba","Elsa","Buzz Lightyear","Woody","Goku","Vegeta","Naruto","Scooby-Doo","Bob Esponja","Jack Sparrow","Indiana Jones","Rambo","Rocky Balboa"],
  "Países":["Brasil","Argentina","Uruguai","Chile","México","Estados Unidos","Canadá","Portugal","Espanha","França","Itália","Alemanha","Inglaterra","Grécia","Egito","Japão","China","Índia","Austrália","Rússia","Suíça","Holanda","Bélgica","Noruega","Suécia","Coreia do Sul","África do Sul","Turquia","Tailândia","Nova Zelândia"],
  "Natureza":["Montanha","Vulcão","Cachoeira","Rio","Lago","Oceano","Floresta","Deserto","Ilha","Caverna","Geleira","Arco-íris","Tornado","Furacão","Terremoto","Neve","Chuva","Relâmpago","Nuvem","Sol","Lua","Estrela","Praia","Pedra","Árvore","Flor","Folha","Areia","Fogo","Gelo"],
  "Casa":["Sofá","Cama","Geladeira","Fogão","Televisão","Chuveiro","Vaso sanitário","Guarda-roupa","Mesa","Cadeira","Janela","Porta","Tapete","Almofada","Travesseiro","Espelho","Lâmpada","Ventilador","Ar-condicionado","Máquina de lavar","Micro-ondas","Liquidificador","Cafeteira","Panela","Talher","Prato","Copo","Toalha","Vassoura","Varal"]
};

const categoryIcons ={Comidas:'🍔',Animais:'🐶',Filmes:'🎬',Lugares:'🌎',Games:'🎮',Objetos:'🎒',Profissões:'👨‍🚒',Esportes:'⚽',Carros:'🚗',Tecnologia:'💻',Música:'🎵',Personagens:'🦸',Países:'🌍',Natureza:'🌿',Casa:'🏠'};

const wordHints ={
  "Internet":"rede","Wi-Fi":"sem fio","Bluetooth":"conexão","Inteligência Artificial":"aprendizado","Robô":"automação","Drone":"voo","Notebook":"portátil","Smartphone":"aplicativos","Tablet":"tela","Impressora 3D":"fabricação","GPS":"localização","Pendrive":"armazenamento","QR Code":"leitura","Nuvem":"remoto","Banco de dados":"informação","Servidor":"hospedagem","Roteador":"rede","Processador":"cálculo","Placa de vídeo":"gráficos","Teclado":"digitação","Mouse":"cursor","Monitor":"imagem","Webcam":"vídeo","Microfone":"áudio","Realidade virtual":"imersão","Satélite":"órbita","Fibra óptica":"velocidade","Código de barras":"produto","Smartwatch":"pulso","Console":"jogos",
  "Pizza":"forno","Sushi":"arroz","Churrasco":"brasa","Feijoada":"feijão","Lasanha":"camadas","Pastel":"fritura","Hambúrguer":"sanduíche","Cachorro-quente":"lanche","Strogonoff":"molho","Risoto":"arroz","Panqueca":"massa","Coxinha":"salgado","Brigadeiro":"chocolate","Pudim":"sobremesa","Sorvete":"gelado","Bolo":"festa","Macarrão":"massa","Batata frita":"crocante","Pão de queijo":"Minas","Tapioca":"mandioca","Churros":"canela",
  "Cachorro":"latido","Gato":"miado","Elefante":"tromba","Girafa":"pescoço","Tubarão":"oceano","Pinguim":"gelo","Leão":"juba","Tigre":"listras","Macaco":"árvore","Cavalo":"galope","Coelho":"orelhas","Urso":"hibernação","Lobo":"alcateia","Raposa":"cauda","Canguru":"bolsa","Panda":"bambu","Golfinho":"mar","Baleia":"oceano","Polvo":"tentáculos","Cobra":"rastejar","Águia":"voo","Coruja":"noite","Tartaruga":"casco",
  "Praia":"areia","Hospital":"saúde","Escola":"aula","Aeroporto":"viagem","Shopping":"lojas","Estádio":"torcida","Cinema":"tela","Restaurante":"refeição","Supermercado":"compras","Academia":"treino","Biblioteca":"livros","Hotel":"hospedagem","Delegacia":"polícia","Parque":"lazer","Zoológico":"animais","Museu":"exposição","Teatro":"palco","Igreja":"fé","Padaria":"pão","Farmácia":"remédio","Banco":"dinheiro","Rodoviária":"ônibus","Metrô":"trilhos","Universidade":"faculdade","Castelo":"realeza","Fazenda":"campo","Floresta":"árvores","Deserto":"seca","Ilha":"mar",
  "Futebol":"gol","Vôlei":"rede","Tênis":"raquete","Natação":"piscina","Basquete":"cesta","Surfe":"onda","Fórmula 1":"velocidade","Boxe":"luvas","MMA":"octógono","Judô":"tatame","Karatê":"faixa","Skate":"manobra","Ciclismo":"pedal","Atletismo":"pista","Handebol":"gol","Golfe":"taco","Rugby":"oval","Beisebol":"taco","Hóquei":"disco","Futsal":"quadra","Ginástica":"flexibilidade","Hipismo":"cavalo","Esqui":"neve","Snowboard":"prancha","Triatlo":"resistência","Escalada":"altura","Motocross":"terra",
  "Sofá":"sala","Cama":"sono","Geladeira":"frio","Fogão":"cozinha","Televisão":"programa","Chuveiro":"banho","Vaso sanitário":"banheiro","Guarda-roupa":"roupas","Mesa":"apoio","Cadeira":"sentar","Janela":"vista","Porta":"entrada","Tapete":"chão","Almofada":"conforto","Travesseiro":"sono","Espelho":"reflexo","Lâmpada":"luz","Ventilador":"vento","Ar-condicionado":"clima","Máquina de lavar":"roupa","Micro-ondas":"aquecer","Liquidificador":"misturar","Cafeteira":"café","Panela":"cozinhar","Talher":"comer","Prato":"refeição","Copo":"bebida","Toalha":"secar","Vassoura":"limpeza","Varal":"roupas"
};

const categoryHints ={Comidas:'refeição',Animais:'ser vivo',Filmes:'cinema',Lugares:'local',Games:'jogo',Objetos:'utilidade',Profissões:'trabalho',Esportes:'competição',Carros:'veículo',Tecnologia:'digital',Música:'som',Personagens:'ficção',Países:'território',Natureza:'ambiente',Casa:'lar',Personalizada:'relacionado'};